### PR TITLE
Write paper for JOSS

### PR DESCRIPTION
**Pull request by oxinabox**
This is blocked by #5 as it says that that is done.

### CODE REVIEW

**Comment by Ayushk4** [comment]
Can I update this with information about TokenBuffer and its lexers to create custom tokenizers? And also other tokenizers - Reversible Tokenizer, Twitter Tokenizers?

**Comment by oxinabox** [comment]
yes, please do, and add self as a coauther, and @MikeInnes and @aquatiko  too.

**Comment by oxinabox** [comment]
@MikeInnes @aquatiko @Ayushk4 
as you are all listed as authors, can you review this,
and if happy indicate so via github apprroval?

Then we can submit this

**Review by MikeInnes — APPROVED** [review]

**Review by aquatiko — APPROVED** [review]

**Review by Ayushk4 — APPROVED** [review]

**Comment by oxinabox** [comment]
Sorry I forgot to action this.
Last thing is I think should swap the author order and put @Ayushk4  as first author,
as they have done much more on this recently than me.

If I don't hear any objections, I will do this and then will merge and submit

**Comment by oxinabox** [comment]
https://github.com/openjournals/joss-reviews/issues/1939

**Pull request merged**
