### PR TITLE
Fix for 1.0

### PR DESCRIPTION
**Pull request by AShedko**
Mostly `replace` changing input params from 4 args to 3.

### CODE REVIEW

**Comment by aviks** [comment]
Hi could you take the changes from #13, and add your `ExtendedTest` removal commit on to that. Then do a new PR with those changes.

**Comment by AShedko** [comment]
Sure.

**Comment by aviks** [comment]
Actually, this is no longer necessary. Lyndon has merged #13, and made all the changes necessary. Thanks for your contributions!

**Comment by oxinabox** [comment]
@AShedko  sorry,
this is on me, there was open PR's that did the same.
Which is my fault, if I had have kept up with merging PRs you wouldn't have ended up making one similar to what was already there in #13.

**Pull request closed without merging**
