### PR TITLE
Fixes Julia 0.7 deprecation warnings

### PR DESCRIPTION
**Pull request by Paethon**

### CODE REVIEW

**Comment by Paethon** [comment]
Seems 1.0 does not work because of TestSetExtensions ...

**Comment by oxinabox** [comment]
LGTM
Thanks

**Comment by aviks** [comment]
So tests fail on 1.0 due to `TestSetExtensions` which does not support 1.0 due to base removing features it depended on. @oxinabox are you open to removing dependency on that package for now?

**Comment by oxinabox** [comment]
I really like it for this.
It is particularly useful for the kind of errors we see here.

But yes,
lets remove it.
it will be easy enough to add back later.

**Comment by oxinabox** [comment]
this caught me off-guard, as I didn't realize it was a PR against my PR,
so merged them in the wrong order.
But with some stuff, I have now fixed that.
Thanks.

**Pull request merged**
